server:
  port: 8006
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/*
      serviceId: ribbon-service
    api-b:
      path: /api-b/*
      serviceId: feign-service
    api-c:
      path: /api-c/*
      serviceId: config-client